### ISSUE TITLE
draft mail

### ISSUE THREAD

**Issue by davidgohel** [rte-antares-rpackage/antaDraft#10]
Draft a mail explaining for a given quality issue, country and area:
- period and datetime where issue occured

**Comment by jalazawa** [comment]
a CSV with the data will be good also.

**Comment by jalazawa** [comment]
rajouter comme info la date de téléchargement des données du FTP

**Comment by jalazawa** [comment]
décalage horaire à corriger dans le résumé des erreurs et dans les rapports. 

Voilà ce que donne le site internet 

ZERO VALUES:
-	Between 
o	2015-07-20 13:00:00 à 2015-07-21 21:00:00
o	2015-07-21 22:00:00 à 2015-07-22 14:00:00

Voilà ce que donne le rapport 

Between 
◦2015-07-20 13:00:00 à 2015-07-21 20:00:00
◦2015-07-21 22:00:00 à 2015-07-22 13:00:00

Il faudrait modifier l'heure de fin de la deuxième date. 
Mais attention, il faut prendre en compte la fréquence de la donnée qui peut être différente en fonction du pays (15min, 30min, 60min). 

Même remarque quand les erreurs sont sur un pas horaire.

**Comment by jalazawa** [comment]
information CTA, BZN ou CTY à mettre dans les rapports "non agrégés"

**Comment by jalazawa** [comment]
YES
