### ISSUE TITLE
Add new rule : Is CTY, CTA or BZN equal to zero?

### ISSUE THREAD

**Issue by FabiolaAravena** [rte-antares-rpackage/antaDraft#11]
Je me suis rendue compte qu'il a des données qui ne sont pas manquantes, mais qui sont égales à zéro. Il faudrait les repérer.

**Comment by davidgohel** [comment]
Cela correspond normalement à **BZN is positive** ou **CTA is positive** ou **CTY is positive**, tu les trouves?

**Comment by FabiolaAravena** [comment]
Oui, mais il faudrait appliquer la règle avant l'agrégation de ces valeurs.

**Comment by davidgohel** [comment]
oui, on va créer une nouvelle fonction pour ça

**Comment by davidgohel** [comment]
une règle à été modifiée : `((CTY - lag(CTY)) / CTY) < .5 & ((lag(CTY) - CTY) / lag(CTY)) < .5` - elle permet de mieux identifier les données aberrantes

**Comment by jalazawa** [comment]
OK
