### ISSUE TITLE
prochain point 

### ISSUE THREAD

**Issue by jalazawa** [rte-antares-rpackage/antaDraft#13]
à discuter 

- est-ce qu'on veut récupérer tous les pas horaires de toutes les données ? 
Par exemple : la consommation allemande au pas 15min. 
Utile ? on peut utiliser une donnée à 16h45 pour corriger une donnée à 17h -> représente 1% des cas ou 40% ?

**Comment by davidgohel** [comment]
Rapport à l'effort à fournir, pour le moment non
