### ISSUE TITLE
invalidité des plages horaires relevées par qualcon 

### ISSUE THREAD

**Issue by davidgohel** [rte-antares-rpackage/antaDraft#14]

**Comment by jalazawa** [comment]
Non, prioritaire :-)

**Comment by davidgohel** [comment]
normalement c'est règlé

**Comment by jalazawa** [comment]
Quel est la variable permettant de connaitre les plages horaires relevées  ? 

CTY _ LAG _ X par exemple ? 

J'ai un doute sur le bon fonctionnement des règles de gradient, cf. cet exemple 

![bug_regles_aggregation](https://user-images.githubusercontent.com/22026724/33118272-98e828e6-cf6b-11e7-99cd-726848027cd9.png)


Je pense qu'il ne faudrait pas activer cette règle quand une  précédente règle a été invalidé. 

Est-ce que se comportement est réalisé pour toutes les règles ? 

ici je vois des FALSE sur les règles de positivité et de gradient. 

Je pose aussi des questions sur la ligne 26, CTA est positif mais on a activité la règle de positivité et aussi de gradient.

**Comment by davidgohel** [comment]
Je vais regarder. Pour la ligne 26, c'est juste une histoire de précision numérique. Je vais modifier les tests à `CTY > .99` si c'est ok pour toi.

**Comment by jalazawa** [comment]
OK
