### ISSUE TITLE
bug : command iconv indisponible sur les machines windows sans cygwinn 

### ISSUE THREAD

**Issue by jalazawa** [rte-antares-rpackage/antaDraft#17]
Il me semble qu'il faudrait 

- [ ] 1. Changer de méthode pour convertir l'encodage (méthode multiplate-forme windows/linux/mac) 
- [ ] 2. Ce bug arrive quand on utilise la fonction entsoe_repository cf. log ci-dessous, il faut donc rajouter des tests sur cette fonction qui seront lancés sur Travis (linux), appveyor (Windows) afin de ne plus avoir ce problème dans le futur. Actuellement cette fonction est testé à 0%, est-ce qu'on peut inclure des mini-fichiers dans le package ? 
 
```R
entsoe_repository(wrangling_dir, perso_data, utf16 = TRUE, force = FALSE)
Error in system(command = cmd_, intern = TRUE) : 'iconv' not found
Called from: system(command = cmd_, intern = TRUE)
```

**Comment by davidgohel** [comment]
Oui, pas de souci. Normalement, cela va etre modifié pour ne devenir qu'une option.

**Comment by jalazawa** [comment]
Yes, merci ! 

encore un petit point, si je commente la ligne qui fait l'encodage (puis que je recompile etc.), j'ai un nouveau bug ici : 

```R
entsoe_repository(wrangling_dir, perso_data, utf16 = TRUE, force = FALSE)
Error in read_tokens_(data, tokenizer, col_specs, col_names, locale_,  : 
  Not compatible with STRSXP: [type=NULL].
In addition: Warning messages:
1: Duplicated column names deduplicated: '' => '_1' [3], '' => '_2' [4], '' => '_3' [5], '' => '_4' [6], '' => '_5' [7], '' => '_6' [8], '' => '_7' [9] 
2: The following named parsers don't match the column names: year, month, day, DateTime, AreaTypeCode, AreaName, MapCode, TotalLoadValue, SubmissionTS 
Called from: read_tokens_(data, tokenizer, col_specs, col_names, locale_, 
    n_max, progress)
Browse[1]> n
```

fonction 

```R
function (sourceSpec, tokenizerSpec, colSpecs, colNames, locale_, 
  n_max = -1L, progress = TRUE) 
{
  .Call("readr_read_tokens_", PACKAGE = "readr", sourceSpec, 
    tokenizerSpec, colSpecs, colNames, locale_, n_max, progress)
}
```

d'après une recherche rapide ça vient peut être de la famille des packages dplyr, readr etc. (version de rcpp différentes ?), je ne sais pas 

[resultatRapide](https://stackoverflow.com/questions/21391113/all-equal-on-object-with-null-names-causes-error-not-compatible-with-strsxp)

La réinstallation des packages n'a rien donné. 

Si le problème est différent et n'a rien à voir avec l'encodage, je suis partant pour qu'on crée un autre ticket.

**Comment by davidgohel** [comment]
il n'y a plus de `readr` et plus d'encodage UTF16
