### ISSUE TITLE
Mécanisme de correction auto des données

### ISSUE THREAD

**Issue by davidgohel** [rte-antares-rpackage/antaDraft#2]
Certaines données sont incomplètes mais peuvent être corrigées mécaniquement. Il faut permettre via un système d'expression YAML la spécification de ces corrections.

Par exemple, si CTY est manquant mais que CTA et BZN sont présents et égaux, on peut remplacer pour tel pays la données CTY par celle de CTA.

**Comment by davidgohel** [comment]
new function `correct_db`

**Comment by jalazawa** [comment]
OK
