### ISSUE TITLE
erreur lors de la construction du package 

### ISSUE THREAD

**Issue by jalazawa** [rte-antares-rpackage/antaDraft#27]
```R
** preparing package for lazy loading
Error : object 'scale_fill_viridis_c' is not exported by 'namespace:ggplot2'
ERROR: lazy loading failed for package 'antaDraft'


```

**Comment by davidgohel** [comment]
Il faut la version remote de ggplot: https://github.com/rte-antares-rpackage/antaDraft/blob/master/DESCRIPTION#L25

Je peux supprimer aussi, ça simplifiera

**Comment by jalazawa** [comment]
Je veux bien simplifier et ne pas dépendre de version sur github avec nos problèmes de proxy etc. ce n'est pas évident.

**Comment by davidgohel** [comment]
c fait

**Comment by jalazawa** [comment]
OK
