### ISSUE TITLE
production de tests par 

### ISSUE THREAD

**Issue by davidgohel** [rte-antares-rpackage/antaDraft#29]
[fait par RTE] Production réalisée comparée à la fin à ce qui est produit par antares (fichiers CSV)

- ActualGenerationOutput : production heure par heure
- ActualConsomption: conso des auxilliaires

Comparer la somme des productions

======  =======

## B02-Production_réalisée_par_groupe

Il ne faut pas faire de tests d'egalite entre CTY/BZN et CTA (il n'y a que CTA)

Colonne "PowerSystemRessouceName" : nom d'un groupe

Prod d'un groupe à chaque instant T, -> ActualGenerationOutput < InstallGenCapacity

ProductuonTypeName : filière

ActualGenerationOutput : production d'un groupe

somme des productions des groupes d'une filère ~ production de la filière ; le tout par production_typename

pour donnée hordatées , vérifier la production du groupe < 1+capcité installée installée du groupe

Somme des capacités des groupes d'une filère ~= capacité de la filière

## fichiers B01-Production_réalisée_par_filière

production de la filière < capacité de la filière
somme des productions des groupes d'une filère ~ production de la filière

## fichiers capacité annuelle

memes validations qu'en consommation mais par productiontype_name

Colonnes :

AggregatedInstalledCapacity : capacité installée de production d'une filière
ProductuonTypeName : filière

---------------------
test = comparer la somme des productions à la consommation

prod + solde des echanges(positif qd on importe, negatif qd on exporte) = consommation

------- Sorties par fichiers

### Capactié annuelle des filières

year, pays, filières, map_code(BZN/CTA/CTY), valeur

### Production des groupes

Date, pays, groupe, filière, valeur de la capacité installée, valeur de la prod réalisée, CTA

## Production des filières

Date, pays, filière, valeur de la prod réalisée, CTA

+++++ Validation croisée entre Prod_groupes et prod filières +++++++

somme de la production des groupes de chaque filière = production de la filière pour chaque CTA, et chaque date
Les données du fichier [Capactié annuelle des filières] - production de la filière < capacité de la filière

-> gros tableau de synthèse des résultats

Aggregatedinstalledcapacity : Mega watt (1000)

mega watt / heure : nombre d'heures dans l'année * AggregatedInstalledCapacity

**Comment by jalazawa** [comment]
j'ai subdivisé le travail ici 

#34 
#35 
#36
