### ISSUE TITLE
mauvaise date et ligne "dupliqué" lors de l'import 

### ISSUE THREAD

**Issue by jalazawa** [rte-antares-rpackage/antaDraft#33]
J'ai constaté des lignes dupliquées sur les données importées. 

Après quelques recherche, il semble que la ligne n'est pas vraiment dupliqué mais une erreur dans l'heure semble provoquée la duplication et la suppression d'une autre ligne. 

Par exemple, si je fais ceci 

```R 
load_db <- anta_load_read(perso_data)

load_db_dt<-as.data.table(load_db)
resIdsLoadDb<-load_db_dt[, .(country, MapCode, AreaTypeCode, DateTime) ]
indexDuplicatedLoadDv<-which(duplicated(resIdsLoadDb) | duplicated(resIdsLoadDb[nrow(resIdsLoadDb):1, ])[nrow(resIdsLoadDb):1])
load_db_dt[indexDuplicatedLoadDv, ] %>% View("duplicated_rows_db")
load_db_dt[MapCode=="LU" & AreaTypeCode=="CTA" & (DateTime=="2015-03-29 01:00:00"| DateTime=="2015-03-29 02:00:00" | DateTime=="2015-03-29 00:00:00" | DateTime=="2015-03-29 03:00:00"), ] %>% View("duplicated_rows_db_lu")


```

j'obtiens ce tableau 

![bug_duplication_lignes](https://user-images.githubusercontent.com/22026724/34614104-93e5aaca-f230-11e7-91be-79cec4d57bd3.png)

Mais sur les fichiers du FTP je constate ceci 

![bug_duplication_lignes_ok_ftp](https://user-images.githubusercontent.com/22026724/34614137-b0e2d4e0-f230-11e7-86ac-5d36d20e3557.png)

On constate alors que la deuxième ligne à "01:00" et en fait la ligne correspondant à la donnée à "02:00". 

Dans le tableau sur R, sur la ligne 3, on devrait lire la date suivante "2015-03-29 02:00:00" correspondante à la valeur 369. 

J'ai aussi constaté qu'il y'a 262 lignes dupliquées dans les données importées. 

On devrait faire une vérification lors de l'import (un assert dans le code ?) afin de s'assurer qu'il n'y a pas de lignes dupliquées dans la table.

**Comment by FabiolaAravena** [comment]
J'ai le même problème de duplication de lignes pour CTA, CTY et BZN pour AUSTRIA. La seule différence est que la ligne dupliquée est "02:00".

Les données sur Rstudio : 
![ligne_duplique_austria_0200_rstudio](https://user-images.githubusercontent.com/26141980/34768061-1990a888-f5fa-11e7-9bdc-4d93eb7e7c7d.PNG)

Sur le FTP : 
![ligne_duplique_austria_0200](https://user-images.githubusercontent.com/26141980/34768087-2d99a9b0-f5fa-11e7-9249-7dcc5d43fad2.PNG)

**Comment by jalazawa** [comment]
C'est ok pour moi et toi @FabiolaAravena ?

**Comment by davidgohel** [comment]
Attention quand on subset une date `posixct`, vous pouvez utiliser la fonction suivante si nécessaire: 

    as_ct <- function(str) fasttime::fastPOSIXct(str, tz = "GMT")

**Comment by FabiolaAravena** [comment]
C'est ok pour moi aussi!
