### ISSUE TITLE
Production réalisée par filière 

### ISSUE THREAD

**Issue by jalazawa** [rte-antares-rpackage/antaDraft#34]
1 - importer les données des productions des filières depuis le fichier "Année_Mois_AggregatedGenerationPerType.csv".
2 - Garder seulement les données aux heures rondes (01:00, 02:00, 03:00 etc.) 
3 - Garder seulement les données du thermique 
4 - vérifier pour chaque instant t que la production de chaque filière 'ActualGenerationOutput' est inférieur ou égal à 'AggregatedInstalledCapacity' par (AreaName, ProductionType_Name, MapCode, AreaTypeCode)   

ATTENTION, la donnée AggregatedInstalledCapacity se trouve dans le fichier "AAAA_Mois_InstalledGenerationCapacityAggregated.csv" 

5 - retirer de la table toutes les filières qui ont une capacité égal à 0 
6 - générer un rapport d'erreur par "ProductionType_Name" , "AreaName", "AreaTypeCode" et  "MapCode" pour toutes les erreurs relevées 

7 - Comparer les valeurs CTA, CTY, BZN pour chaque PAYS en utilisant les règles définies dans cty_rules.yaml 
8 - générer un deuxième rapport d'erreur par "AreaTypeCode" et "ProductionType_Name" , "AreaName" et  "MapCode" pour toutes les erreurs relevées avec les données agrégées.

**Comment by jalazawa** [comment]
Qu'est qui est du thermique ? réponse ...

Fossil Coal-derived gas 
Fossil Brown coal/Lignite 
Fossil Oil 
Fossil Gas 
Fossil Hard coal 
Fossil Oil shale 
Fossil Peat 
Nuclear 
Other

**Comment by jalazawa** [comment]
Pour la liste des pays ayant une filière other cf. #38

**Comment by davidgohel** [comment]
Je le remet dans progress temporairement, il faut de la doc et des exemples.

**Comment by davidgohel** [comment]
La fonction s'appelle `anta_prod_channel`, il reste les exemples et le README à enrichir avec des exemples.

**Comment by jalazawa** [comment]
Si possible modifier le nom de la fonction `anta_prod_channel` par `anta_prod_type` et aussi dans la doc 

```R
import production data per channels from an entsoe repository

Description

import csv data representing production per channels data from an entsoe repository.

Usage

anta_prod_channel(production_dir = NULL, capacity_dir = NULL)
```

**Comment by davidgohel** [comment]
pas de souci, je les laisse dans in progress jusqu'à ce que la doc soit ok

**Comment by jalazawa** [comment]
Je constate un bug sur la fonction `read_prod_type`

cf. code 

```R

library(antaDraft)
> perso_data_type<-"D:\\Users\\jalazawa\\Documents\\2_ANTARES\\Dev\\packages\\transparency\\data_20180104\\B-PRODUCTION\\B01-Production_réalisée_par_filière\\2016"
> perso_data_type_capa2016<-"D:\\Users\\jalazawa\\Documents\\2_ANTARES\\Dev\\packages\\transparency\\data_20180104\\B-PRODUCTION\\B06-Capacité_installée_par_filière\\2016"
> perso_data_prod2016<-"D:\\Users\\jalazawa\\Documents\\2_ANTARES\\Dev\\packages\\transparency\\data_20180104\\B-PRODUCTION\\B02-Production_réalisée_par_groupe\\2016"
> res2016<-read_prod_type(
+   production_dir =perso_data_type,
+   capacity_dir = perso_data_type_capa2016,
+   production_file =perso_data_prod2016
+ )
Error in file(con, "r") : cannot open the connection
In addition: Warning message:
In file(con, "r") :
  cannot open file 'D:\Users\jalazawa\Documents\2_ANTARES\Dev\packages\transparency\data_20180104\B-PRODUCTION\B02-Production_réalisée_par_groupe\2016': Permission denied
```

Mais lorsqu'on essaie de lire les productions de groupe tout se passe bien 

```R

global_options <- getOption("global_options")
> prod_by_group <- read_prod_group(production_dir = perso_data_prod2016,
+                                  production_file = global_options$thermal_production_per_country)
Read 1491973 rows and 10 (of 13) columns from 0.185 GB file in 00:00:03
Read 1528740 rows and 10 (of 13) columns from 0.192 GB file in 00:00:03
Read 1301973 rows and 10 (of 13) columns from 0.162 GB file in 00:00:03
Read 1442886 rows and 10 (of 13) columns from 0.180 GB file in 00:00:03
Read 1528722 rows and 10 (of 13) columns from 0.190 GB file in 00:00:03
Read 1473318 rows and 10 (of 13) columns from 0.184 GB file in 00:00:03
Read 1492540 rows and 10 (of 13) columns from 0.186 GB file in 00:00:03
Read 1413650 rows and 10 (of 13) columns from 0.176 GB file in 00:00:03
Read 1496956 rows and 10 (of 13) columns from 0.186 GB file in 00:00:03
Read 1502208 rows and 10 (of 13) columns from 0.187 GB file in 00:00:03
Read 1464520 rows and 10 (of 13) columns from 0.182 GB file in 00:00:04
> names(prod_by_group)
 [1] "DateTime"           "MapCode"            "AreaTypeCode"      
 [4] "production_type"    "country"            "AreaName"          
 [7] "group_name"         "generation_output"  "consumption"       
[10] "installed_capacity" "observed"
```

**Comment by davidgohel** [comment]
L'argument `production_file` de `read_prod_type()` est un chemin vers un fichier YAML comme celui ci: 

https://github.com/rte-antares-rpackage/antaDraft/blob/master/inst/config/global/renewable_production.yml

Je vais mieux documenter la chose

**Comment by jalazawa** [comment]
OK Merci
