### ISSUE TITLE
Production réalisée par groupe

### ISSUE THREAD

**Issue by jalazawa** [rte-antares-rpackage/antaDraft#35]
Dans un premier temps pour l'année 2016 

1 - Importer les données des fichiers "Année_Mois_ActualGenerationOutputPerUnit.csv" 
2 - Garder seulement les données aux heures rondes (01:00, 02:00, 03:00 etc.) 
3 - Garder seulement les données du thermique 
4 - A chaque instant t, vérifier que "ActualGenerationOutput" est inférieur ou égal à "InstalledGenCapacity"
5 - si ce n'est pas le cas, générer un rapport d'erreur par "PowerSystemResourceName" avec toutes les erreurs relevées avec les infos "ProductionType_Name" , "AreaName" et  "MapCode" pour toutes les erreurs relevées

**Comment by davidgohel** [comment]
La fonction s'appelle `anta_prod_group`, il reste les exemples et le README à enrichir avec des exemples.

**Comment by jalazawa** [comment]
OK
