### ISSUE TITLE
other : regarder les capa pour la config  

### ISSUE THREAD

**Issue by jalazawa** [rte-antares-rpackage/antaDraft#38]
pour moi

**Comment by jalazawa** [comment]
Voila les pays ayant une filière "other" thermique 

- AUSTRIA
- BELGIUM
- FRANCE 
- GERMANY
- IRELAND
- ITALY
- LUXEMBOURG
- NETHERLANDS
- NORTH_IRELAND
- PORTUGAL
- SPAIN
- UK

**Comment by davidgohel** [comment]
Merci, tu es sûr pour BELGIUM? je n'en observe jamais.

**Comment by jalazawa** [comment]
Oui, j'en suis sur, explication

Il n'y a pas de capacité déclarée dans le fichier Excel "2017_1_InstalledGenerationCapacityAggregated.csv" pour "other" "BELGIUM", cf image 

![no_capacity](https://user-images.githubusercontent.com/22026724/34827262-d9669fb6-f6d9-11e7-949b-f444884f8b00.png)


**MAIS** dans le fichier "2016_6_AggregatedGenerationPerType.csv" on constate de la production "other" pour "BELGIUM", cf. image 

![no_capacity_but_power](https://user-images.githubusercontent.com/22026724/34827394-4d9afdaa-f6da-11e7-8151-00ade46af9ce.png)

On doit pouvoir récupérer la production spécifier dans le fichier "2016_6_AggregatedGenerationPerType.csv"  et l'utiliser lors de la comparaison de BZN/CTY et CTA même si dans le fichier "2017_1_InstalledGenerationCapacityAggregated.csv", il n'y a pas de capacité spécifier. 

Un des résultats attendu des rapport est : 
- Donnée non observée pour la capacité "other" de BELGIUM 

On pourra stocker un NA dans la colonne capacity pour cette filière. 

L'idée à la fin est d'envoyer un mail si la capacité n'est pas rentrée dans le site (ou FTP) alors qu'il y'a de la production à certains moments.

**Comment by jalazawa** [comment]
Yes
