### ISSUE TITLE
[prod] NA au lieu de 0 pour plusieurs filières sur SPAIN

### ISSUE THREAD

**Issue by jalazawa** [rte-antares-rpackage/antaDraft#40]
Ce que je constate sur le FTP 
![capa_ftp](https://user-images.githubusercontent.com/22026724/35043761-175d703e-fb8e-11e7-9c0e-513a63c1a28e.png)

Ce que je constate sur RStudio 

![capa_r](https://user-images.githubusercontent.com/22026724/35043770-1e7e49b0-fb8e-11e7-9099-62532f069557.png)

Le code pour retrouver l'anomalie : 

Au lieu d'avoir un NA on devrait avoir un 0. 

```R

perso_data_channel<-"D:\\Users\\jalazawa\\Documents\\2_ANTARES\\Dev\\packages\\transparency\\data_20180104\\B-PRODUCTION\\B01-Production_réalisée_par_filière\\2016"

perso_data_channel_capa2016<-"D:\\Users\\jalazawa\\Documents\\2_ANTARES\\Dev\\packages\\transparency\\data_20180104\\B-PRODUCTION\\B06-Capacité_installée_par_filière\\2016"


res2016<-anta_prod_channel(
  production_dir =perso_data_channel,
  capacity_dir = perso_data_channel_capa2016
)

res2016Valid<-augment_validation(res2016)

res2016Valid[ res2016Valid$DateTime=="2016-01-01 02:00:00" & res2016Valid$AreaTypeCode=="BZN" & res2016Valid$country=="SPAIN" & (res2016Valid$production_type=="Fossil Coal-derived gas" | res2016Valid$production_type=="Fossil Gas")  ,] %>% View("es_bzn_ca")



```

**Comment by jalazawa** [comment]
Même chose pour ces 2 filières : 

- Fossil Peat 
- Fossil Oil shale 

FTP 

![capa_ftp_2](https://user-images.githubusercontent.com/22026724/35044014-06ae9e7e-fb8f-11e7-9c73-edb75478876d.png)


RStudio 

![capa_r_2](https://user-images.githubusercontent.com/22026724/35044022-0cee44ec-fb8f-11e7-81bc-a680dab697a9.png)

**Comment by davidgohel** [comment]
Oui, c'est ce qui a été implémenté #34 au point 5. On peut le changer facilement.

**Comment by jalazawa** [comment]
En fait, c'est un vrai/faux problème. La production de ces filières est toujours nulles. 
Je propose de ne rien modifier pour l'instant. 

Je clôture le ticket.
